FROM python:3.11-slim-buster

RUN apt-get update && apt-get install -y \
    curl \
    git \
    jq \
    make \
    net-tools

# Install Poetry
RUN curl -sSL https://install.python-poetry.org | python3 -

# Define environment variable for poetry config
ENV POETRY_VERSION=1.6.1

# Expose Jupyter ports
EXPOSE 8888
EXPOSE 6789

# Set default entrypoint (Jupyter Lab)
CMD ["jupyter", "lab", "--allow-root", "--NotebookApp.open_browser=False"]

# Optional customizations
# Add VS Code extensions in devcontainer.json
# See https://aka.ms/devcontainer.json for details

# Don't copy any files or create users during build